import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getFeeds } from './feedsAPI';

const initialState = {
  value: 0,
  status: 'idle',
  posts: []
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.


export const getFeedsAsync = createAsyncThunk(
  'feeds/getFeeds',
  async (token) => {
    const response = await getFeeds(token);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const feedsSlice = createSlice({
  name: 'feeds',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      
      .addCase(getFeedsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getFeedsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.posts = action.payload;
      });
  },
});


// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state) => state.counter.value;
export const selectFeeds = (state) => state.feeds.posts;
// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default feedsSlice.reducer;
